{% set name = "mdv" %}
{% set version = "1.7.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdv-{{ version }}.tar.gz
  sha256: eb84ed52a2b68d2e083e007cb485d14fac1deb755fd8f35011eff8f2889df6e9

build:
  number: 0
  noarch: python
  entry_points:
    - mdv = mdv:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.9
  run:
    - markdown
    - pygments
    - python >=3.6,<3.9
    - tabulate

test:
  imports:
    - mdv
  commands:
    - pip check
    - set PYTHONUTF8=1
    - mdv --help
  requires:
    - pip

about:
  home: http://github.com/axiros/terminal_markdown_viewer
  summary: Terminal Markdown Viewer
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
